package com.StockAppBackend.fullstackbackend.TemplateMethod;

import com.StockAppBackend.fullstackbackend.entity.TextRecommendation;

import java.util.List;

public class PdfStockRecommendationGenerator extends StockRecommendationGenerator {

    @Override
    protected void generateContent(List<TextRecommendation> textRecommendation) {
        System.out.println("PDF: Analyzing stock trends and making recommendations...");
    }

    @Override
    protected void generateFooter() {
        System.out.println("PDF: Generated by StockRecommendationGenerator");
    }

}
