package com.StockAppBackend.fullstackbackend.TemplateMethod;

import com.StockAppBackend.fullstackbackend.entity.TextRecommendation;

import java.util.List;

public class WordStockRecommendationGenerator  extends StockRecommendationGenerator{

    @Override
    protected void generateContent(List<TextRecommendation> textRecommendation) {
        System.out.println("Word: Analyzing stock trends and making recommendations...");
    }

    @Override
    protected void generateFooter() {
        System.out.println("Word: Generated by StockRecommendationGenerator");
    }
}
